assets:
  - wordpress_github.sql.gz
steps:
  - name: Check wp-cli.
    plugin: Script
    script:
      - wp --info --allow-root
  - name: Update wp-cli.
    plugin: Script
    script:
      - wp cli update --allow-root --yes
  - name: Check wp-cli version again.
    plugin: Script
    script:
      - wp --info --allow-root
  - name: Site setup
    plugin: WordPressApp
    database: 'wordpress_github.sql.gz'
    databaseName: 'wordpress'
    databaseGzipped: true
    subDirectory: 'code'
    devDomain: 'http://example.com'
    devHome: 'http://example.com/'
    flushCaches: true
  - name: Create admin user.
    plugin: Script
    script:
      - wp user create admin dev@probo.ci --role=administrator --allow-root
